--- #YAML:1.0
name:               Wx-Perl-PodBrowser
version:            2
abstract:           POD browser in Wx.
author:
    - Kevin Ryde <user42@zip.com.au>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:          5.008
    Wx:            0
    Wx::RichText:  0
resources:
    homepage:  http://user42.tuxfamily.org/wx-perl-podbrowser/index.html
    license:   http://www.gnu.org/licenses/gpl.html
no_index:
    directory:
        - t
        - inc
        - devel
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
optional_features:
    maximum_interoperation:
        description:  All the optional things Wx-Perl-PodBrowser can use.
        requires:
            Software::License::GPL_3:  0
